### ISSUE TITLE
Overly verbose property description

### ISSUE THREAD

**Issue by brobichaud** [superstator/Swaggeratr#10]
A number of properties are showing up with very verbose types. This not only is leaking info people don;t need but is also confusing to most I suspect. For example:

Digimarc.Shared.Contracts.ServiceEnumResp {
NumServices (integer),

Services (System.Collections.Generic.List`1[[Digimarc.Shared.Contracts.ServiceReadResp, Digimarc.Contracts, Version=1.26.14.5308, Culture=neutral, PublicKeyToken=null]])
}

**Comment by superstator** [comment]
This is fixed by the recent container support updates in v2013.10.21.1
