### ISSUE TITLE
Accept header support doesn't switch

### ISSUE THREAD

**Issue by brobichaud** [superstator/Swaggeratr#26]
I like the new support for he Accept header. But if you use it with say xml, then switch it to json and try again the response body does not change.

**Comment by superstator** [comment]
When I look at it in Fiddler, the Accept header is being set on the request, but I'm using Chrome. I assume you're using IE?

**Comment by brobichaud** [comment]
Yeah it does seem to be IE specific. I just tried Chrome and it worked fine. I'm running IE11.

**Comment by superstator** [comment]
Going to call this a swagger-ui bug if anything. Won't be fixable here...
