### ISSUE TITLE
Reponse class shows native types - adds no value

### ISSUE THREAD

**Issue by brobichaud** [superstator/Swaggeratr#28]
The response class section details some native types, such as System.Guid or System.Decimal, yet the structure offers no value. Can they be filtered out?

**Comment by makotogitdev** [comment]
Also the same problem with: 
System.Int16
System.Void
System.IAsyncResult
System.IO.Stream
System.AsyncCallBack
System.Object
System.Guid

**Comment by makotogitdev** [comment]
Fixed in #34 . For operations that return non-built-in types, it will be addressed in #32 .
