### ISSUE TITLE
Investigate on having a nav pane on the left with common paths

### ISSUE THREAD

**Issue by makotogitdev** [superstator/Swaggeratr#54]
Can we do something like this easily where we have navigation pane on the left with methods with common paths? Probably just some CSS tweaks.

https://www.callfire.com/api-documentation/rest/version/1.1
![callfirescreencap](https://cloud.githubusercontent.com/assets/5796719/2756649/e4a67338-c979-11e3-90e8-37c5312dfeaa.jpg)

**Comment by superstator** [comment]
This is really a swagger-ui thing rather than a swaggeratr issue.
