### ISSUE TITLE
Does swaggeratr generate an api-docs.json file by default?

### ISSUE THREAD

**Issue by bezz92** [superstator/Swaggeratr#67]
After following the walkthrough I did not see an api-docs.json get generated, is it supposed to?

**Comment by superstator** [comment]
You should be able to request it and see a json result. I think the default now is just api-docs without the .json, though. Ultimately it's whatever you configured in your Global.asax.cs

**Comment by bezz92** [comment]
Yes, after requesting it from my rest service I see a .json result that I can download and save. Thanks!
