### ISSUE TITLE
Not all parameters are required

### ISSUE THREAD

**Issue by brobichaud** [superstator/Swaggeratr#8]
Our api has lots of option parameters, especially query params. The try It Out feature seems to think they are all required.

**Comment by superstator** [comment]
How about this: we continue to default path & body params to required, and default query params to !required. Then add a [ParameterSettings] attribute to allow overriding those (and maybe other) defaults for a specific parameter?

**Comment by brobichaud** [comment]
Yeah this seems like a reasonable approach.
